In [100]:
from sklearn import datasets, tree, model_selection
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score
import pandas as pd

In [101]:
df = pd.read_csv('winequality-red.csv', delimiter=";")


In [102]:
df
# Có 1599 thuộc tính


fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [103]:
print(df['quality'].unique())
# Có 6 nhãn [5 6 7 4 8 3]

[5 6 7 4 8 3]


In [104]:
X = df.drop('quality', axis=1)
y = df.quality


In [105]:
X_train, X_test, y_train, y_test = model_selection.train_test_split(X, y, test_size=4/10)

In [106]:
model = tree.DecisionTreeClassifier()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [107]:
print(accuracy_score(y_test, y_pred))
# 0.6171875

0.6171875


In [108]:
print(confusion_matrix(y_test, y_pred))

[[  0   1   6   0   0   0]
 [  0   2   9   5   1   0]
 [  1   5 201  63   4   0]
 [  0   6  69 150  23   0]
 [  0   0  11  33  40   3]
 [  0   0   0   2   3   2]]


In [109]:
print(precision_score(y_test, y_pred, average=None))

[0.         0.14285714 0.67905405 0.59288538 0.56338028 0.4       ]
